### ISSUE TITLE
Multiple bots

### ISSUE THREAD

**Issue by rafuck** [php-telegram-bot/laravel#51]
Hello, I have been using the package for some time, and now I want to add more bots, like I want to create new console command for another bot which will have its own fetch loop, any idea?

**Comment by TiiFuchs** [comment]
This package and the library php-telegram-bot itself does not (easily if at all) support multiple bots in the same application. This is because most of the functions used to interact with a bot are statically available and have therefore no way to distinguish between multiple bot instances. There is no fix planned for that in the near future.
